version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.11-management-alpine
    networks:
      - poc.mt-network
      
  redis:
    container_name: redis
    image: redis:6.0.10-alpine
    networks:
      - poc.mt-network
      
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - poc.mt-network
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.2
    depends_on:
      - elasticsearch
    networks:
      - poc.mt-network
    
  sql-server-db:
    container_name: azure-sql-edge
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 1434:1433
    environment:
        - ACCEPT_EULA=1
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - poc.mt-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ../grafana/storage:/var/lib/grafana
    networks:
      - poc.mt-network
      
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../prometheus/storage:/prometheus
    networks:
      - poc.mt-network
      
volumes:
  esdata:
  sqldata:
networks:
  poc.mt-network:
    external: true